### ISSUE TITLE
Landlord comments on fit plan...

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/ULI-44_E_Mifflin-Suite_802#3]
Hi @yorikvanhavre,

A few notes here... https://github.com/OpeningDesign/ULI-44_E_Mifflin-Suite_802/commit/f5c381cc45f492080493366e23f734535bf12265?short_path=77a47e7#diff-77a47e7bb301e57665318ca11e42519e

and other notes from landlord here...

> -  Of the plan options sent, the one that most closely represents what was discussed is Option 2.  The tenant does not/will not have a reception function, so that can be eliminated.
> - Please do not mention the polycarbonate on the plans until I’ve had a chance to look at it and compare the cost against clear glass…
> - Can you please send me a version of this plan with the furniture layer turned off so that the construction notes are clearer?  I think the tenant will need a clear plan with dimension strings so that it can layout its own furniture on the plans.

**Comment by yorikvanhavre** [comment]
Done with 7767160
